### ISSUE TITLE
404 error with /app/components/kaarousel/templates/angular-kaarousel.html

### ISSUE THREAD

**Issue by angel1st** [corentin-gautier/angular-kaarousel#13]
Hi there,
I have just installed most recent version - 2.0.3 (I was on 2.0.1 so far), intending to fix https://github.com/corentin-gautier/angular-kaarousel/issues/10 issue.
Please note, I am using bower to install the version, so I have got only **build** folder on my end.
Unfortunately, after the build, I have got following error reported and carousel is totally missing from the view:

`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:61355/app/components/kaarousel/templates/angular-kaarousel.html`

Please advise how to proceed on this, thanks!

**Comment by maximelafarie** [comment]
@angel1st So let me understand: you just changed the angular-kaarousel version into your `bower.json` file and then re-launched the project? If so, you've done it wrong: let the version you want for angular-kaarousel in the `bower.json` file (2.0.3), remove the `bower_components` folder, then do `bower install` then `gulp serve` and see if it fix that bug.

If you already done these steps, then give us a working jsfiddle or a screenshot of the errors in the dev console. It's strange because @corentin-gautier test all of the new features and I'm currently on a working demo.

**Comment by corentin-gautier** [comment]
@maximelafarie I think it's the templateCache module name which isn't what it should be, be there was a PR that was supposed to have fixed that. I need to look more into why this happen

**Comment by corentin-gautier** [comment]
@maximelafarie ok I found the error (see bd65256). Just need to rebuild & re-release, will do that later today

**Comment by angel1st** [comment]
@maximelafarie - I have just pull 2.0.3 via bower and I can confirm the sources in **build** folder is the most recent ones. I see no reason to execute `gulp server` and I believe @corentin-gautier identified the real issue actually.
Thus I hope the fix will be provided.

Cheers,
Angel

**Comment by maximelafarie** [comment]
@angel1st Okay, that was just to provide an example. ;) 
@corentin-gautier Well done! :)
